stages:
  - run

pray:pc205:
  stage: run
  tags:
    - benchmark
    - pc205
  only:
    - master
  script:
    - if [[ -f ~/pdmkp_env ]]; then . ~/pdmkp_env; fi
    - nvidia-smi -L
    - /usr/local/cuda/bin/nvcc --version
    - c++ --version
    - rm -rf ./out
    - mkdir out
    - cd out
    - cmake -G"Unix Makefiles" -DNVCC_ARCH_ARG:STRING=arch=compute_20,code=sm_21 ..
    - make
    - ~/pdmkp_testing/utils/run_tests.sh ./Pray
    - ~/pdmkp_testing/utils/run_benchmarks.sh ./Pray
    
pray:pc205:nobench:
  stage: run
  tags:
    - pc205
  only:
    - pre-master
    - sequential
  script:
    - if [[ -f ~/pdmkp_env ]]; then . ~/pdmkp_env; fi
    - nvidia-smi -L
    - /usr/local/cuda/bin/nvcc --version
    - c++ --version
    - rm -rf ./out
    - mkdir out
    - cd out
    - cmake -G"Unix Makefiles" -DNVCC_ARCH_ARG:STRING=arch=compute_20,code=sm_21 ..
    - make
    - ~/pdmkp_testing/utils/run_tests.sh ./Pray
    
pray:pc189:
  stage: run
  tags:
    - benchmark
    - pc189
  only:
    - master
  script:
    - if [[ -f ~/pdmkp_env ]]; then . ~/pdmkp_env; fi
    - nvidia-smi -L
    - /usr/local/cuda/bin/nvcc --version
    - /opt/rh/devtoolset-4/root/usr/bin/c++ --version
    - rm -rf ./out
    - mkdir out
    - cd out
    - cmake -G"Unix Makefiles" -DNVCC_COMPILER_ARG:STRING=/opt/rh/devtoolset-4/root/usr/bin/c++ -DNVCC_ARCH_ARG:STRING=arch=compute_35,code=sm_35 ..
    - make
    - ~/pdmkp_testing/utils/run_tests.sh ./Pray
    - ~/pdmkp_testing/utils/run_benchmarks.sh ./Pray
    
pray:pc189:nobench:
  stage: run
  tags:
    - pc189
  only:
    - pre-master
    - sequential
  script:
    - if [[ -f ~/pdmkp_env ]]; then . ~/pdmkp_env; fi
    - nvidia-smi -L
    - /usr/local/cuda/bin/nvcc --version
    - /opt/rh/devtoolset-4/root/usr/bin/c++ --version
    - c++ --version
    - rm -rf ./out
    - mkdir out
    - cd out
    - cmake -G"Unix Makefiles" -DNVCC_COMPILER_ARG:STRING=/opt/rh/devtoolset-4/root/usr/bin/c++ -DNVCC_ARCH_ARG:STRING=arch=compute_35,code=sm_35 ..
    - make
    - ~/pdmkp_testing/utils/run_tests.sh ./Pray
